#!/bin/sh

# We start in <repo>/gcc/cobol/scripts
# Switch back to the repository:
cd $( git rev-parse --show-toplevel)
mkdir -p build
cd build
rm -fr *
../configure					\
	--enable-languages=c,c++,cobol		\
	--prefix=/usr/local/gcobol				\
	--disable-bootstrap			\
	--disable-multilib			\
$END

make -j $(nproc)


