name: fetch-rebase-test

# Run this workflow every week
on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:

jobs:    
  fetch-rebase-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true
          ref: current
      - name: Add remote
        run: |
          git remote add gcc git://gcc.gnu.org/git/gcc.git          
      - name: Fetch
        run: |
          git fetch gcc master
      - name: Rebase
        run: |
          git log gcc/master -1
          git config --global user.email "erozen@microsoft.com"
          git config --global user.name "Eugene Rozenfeld"
          git rebase gcc/master
      - name: Check commits
        run: |
          git status
          git log -15
                
      - name: Run build script
        run: | 
          chmod +x .github/scripts/build-gcc.sh
          .github/scripts/build-gcc.sh
        shell: bash
